DROP TABLE Revenue;
DROP TABLE Invoice ;
DROP TABLE Agent;
DROP TABLE Supplier;
DROP TABLE Product;
DROP TABLE Printer;
DROP TABLE Buyer;

DELETE FROM Revenue CASCADE;
DELETE FROM Date CASCADE;
DELETE FROM Invoice CASCADE;
DELETE FROM Agent CASCADE;
DELETE FROM Supplier CASCADE;
DELETE FROM Product CASCADE;
DELETE FROM Printer CASCADE;
DELETE FROM Buyer CASCADE;

SELECT * FROM Buyer;
SELECT * FROM Printer;
SELECT * FROM Product;
SELECT * FROM Supplier;
SELECT * FROM Agent;
SELECT * FROM Invoice;
SELECT * FROM Date;
SELECT * FROM Revenue;